---
name: Close sub-split PRs

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    schedule:
        - cron: "30 7 * * *"

jobs:
    close_subsplit_prs:
        runs-on: ubuntu-latest
        name: Close sub-split PRs
        steps:
            - uses: frankdejonge/action-close-subsplit-pr@0.1.0
              with:
                  close_pr: "yes"
                  # access_token: '{{ secrets.GH_PAT }}' // Uncomment to use self-defined access token, default: ${{ github.token }}
                  # target_branch_match: '.+' // Uncomment to supply your own PR target branch filter
                  message: |
                      Hi :wave:,

                      Thank you for contributing to `css-sizing`. Unfortunately, you've sent a PR to a read-only sub-split repository.
                      All pull requests should be directed towards: https://github.com/row-bloom/row-bloom
